version: "3.8"
services:
  root:
    build:
      context: FoxStudios-EurekaRoot
    ports:
      - '8081:8081'
  loadbalancer:
    build:
      context: FoxStudios-Gateway
    ports:
      - '8082:8082'
  neuro:
    build:
      context: FoxStudios-PyBid
      target: builder
    stop_signal: SIGINT
    ports:
      - "9090:9090"
    deploy:
      mode: replicated
      replicas: 1
