services:
  web:
    build:
      context: FoxStudios-PyBid
      target: builder
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    ports:
      - '9090:9090'
